---
services:
  sender-receiver:
    image: registry.gecko.network/u6bkep/packet-flow:latest
    container_name: packet_flow
    environment:
      - RUST_LOG=info
      - PACKET_FLOW_MODE=sender
      - PACKET_FLOW_REMOTE_ADDR=b-gateway.intern.gecko.network:8651
      - PACKET_FLOW_RATE=100
      - PACKET_FLOW_LOCAL_ADDR=0.0.0.0:8651
      - PACKET_FLOW_INFLUX_URL=http://influxdb.b.intern.gecko.network:8086
      - PACKET_FLOW_DATABASE=packet_flow
      - PACKET_FLOW_TOKEN=rqEqiV9z3iBWLsy0pGIN-NZZdJc-lwuSc_aMpbU_ch5wXmEzC99mwE-n1bSJW3I5H3xtDfDLqjcOd52kWMDdKg==
    restart: unless-stopped
    ports:
      - "0.0.0.0:8651:8651"